In [1]:
import gym
import datetime as dt
import tensorflow as tf
import random
import numpy as np
import math
from tensorflow.keras.layers import Dense, Input

STORE_PATH = '/run'
MAX_EPSILON = 1
MIN_EPSILON = 0.01
LAMBDA = 0.0005
GAMMA = 0.95
BATCH_SIZE = 32
TAU = 0.08
RANDOM_REWARD_STD = 1.0
env = gym.make("CartPole-v1")
# env = gym.make("MountainCar-v0")
state_size = 4
num_actions = env.action_space.n

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense


class QN(tf.keras.Model):
    def __init__(self, layer=0):
        super(QN,self).__init__()
        self.l1 = Dense(2, input_shape=(1,), kernel_initializer='random_uniform',
                bias_initializer='random_uniform')
        self.l2 = Dense(2, kernel_initializer='random_uniform',
                bias_initializer='random_uniform')
        self.l3 = Dense(1, kernel_initializer='random_uniform',
                bias_initializer='random_uniform')
        
    def call(self, input):
        state, action = input
        features = tf.concat([state, action], axis=1)
        feat = tf.nn.relu(self.l1(features))
        feat = tf.nn.relu(self.l2(feat))
        value = self.l3(feat)
        return tf.nn.tanh(value)*2 #Tanh image is [-1,1]
    

In [59]:
cc = QN()

inps = [[np.array([1.]), np.array([1.])],[np.array([2.]), np.array([1.])]]
print(cc(inps))

inps = [[[1.], [3.22]],[[22.],[33.]]]
print(cc(inps))

W1029 21:08:30.927265 140711279597376 base_layer.py:1814] Layer qn is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



tf.Tensor(
[[-0.00765003]
 [-0.00759885]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-0.0073232 ]
 [-0.00638893]], shape=(2, 1), dtype=float32)


In [68]:
single_input = [[np.array([1.])], [np.array([0.])]]

In [69]:
print(cc(single_input))

tf.Tensor([[-0.00754266]], shape=(1, 1), dtype=float32)


In [71]:
np.random.random(4)

array([0.55161186, 0.5564295 , 0.2525965 , 0.52409683])

In [7]:
import gym
import datetime as dt
import tensorflow as tf
import random
import numpy as np
import math
from tensorflow.keras.layers import Dense, Input

STORE_PATH = '/run'
MAX_EPSILON = 1
MIN_EPSILON = 0.01
LAMBDA = 0.0005
GAMMA = 0.95
BATCH_SIZE = 32
TAU = 0.08
RANDOM_REWARD_STD = 1.0
env = gym.make("CartPole-v1")
# env = gym.make("MountainCar-v0")
state_size = 4
num_actions = env.action_space.n

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense


class QN(tf.keras.Model):
    def __init__(self, layer=0):
        super(QN,self).__init__()
        self.l1 = Dense(2, input_shape=(4,), kernel_initializer='random_uniform',
                bias_initializer='random_uniform')
        self.l2 = Dense(2, kernel_initializer='random_uniform',
                bias_initializer='random_uniform')
        self.l3 = Dense(1, kernel_initializer='random_uniform',
                bias_initializer='random_uniform')
        
    def call(self, input):
        feat = tf.nn.relu(self.l1(input))
        feat = tf.nn.relu(self.l2(feat))
        value = self.l3(feat)
        return tf.nn.tanh(value)*2 #Tanh image is [-1,1]
    

In [23]:
state = np.random.random((4))

In [9]:
c = QN()

In [31]:
states = [ np.random.random(4), np.random.random(4)  ]

In [35]:
st = np.expand_dims(states, axis=0)

In [36]:
st

array([[[0.98695742, 0.18361372, 0.84279211, 0.92290387],
        [0.02988309, 0.47629938, 0.87602418, 0.92849264]]])

In [37]:
c(st)

<tf.Tensor: id=265, shape=(1, 2, 1), dtype=float32, numpy=
array([[[-0.02998872],
        [-0.02998872]]], dtype=float32)>

In [17]:
c(state)

InvalidArgumentError: Matrix size-incompatible: In[0]: [4,2], In[1]: [4,2] [Op:MatMul] name: qn_1/dense_3/Tensordot/MatMul/

In [16]:
state

array([[[0.85517099, 0.54594726],
        [0.47715526, 0.17576636],
        [0.38080091, 0.43562652],
        [0.12957113, 0.05465773]]])